services:
  web:
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: ./zarf/docker/web.dockerfile
    env_file:
      - .env.prod
    networks:
      - citadel

  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - citadel

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - citadel_redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass PCDmwMtyKVge8oLd2t81eYVX7EwVmmxK

  postgres:
    image: "postgres:13"
    restart: unless-stopped
    environment:
      PGPASSWORD: citadel
      POSTGRES_DB: PCDmwMtyKVge8oLd2t81eYVX7EwVmmxK
      POSTGRES_USER: citadel
      POSTGRES_PASSWORD: PCDmwMtyKVge8oLd2t81eYVX7EwVmmxK
    ports:
      - "5432:5432"
    volumes:
      - "citadel_postgres:/var/lib/postgresql/data"
    networks:
      - citadel

volumes:
  citadel_postgres:
    name: citadel_postgres
  citadel_redis:
    name: citadel_redis
  caddy_data:
  caddy_config:

networks:
  citadel:
